/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.fichajes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tarea service. Represents a row in the &quot;Fichajes_Tarea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.vass.fichajes.model.impl.TareaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.vass.fichajes.model.impl.TareaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tarea
 * @see es.vass.fichajes.model.impl.TareaImpl
 * @see es.vass.fichajes.model.impl.TareaModelImpl
 * @generated
 */
@ProviderType
public interface TareaModel extends BaseModel<Tarea> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tarea model instance should use the {@link Tarea} interface instead.
	 */

	/**
	 * Returns the primary key of this tarea.
	 *
	 * @return the primary key of this tarea
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tarea.
	 *
	 * @param primaryKey the primary key of this tarea
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tarea ID of this tarea.
	 *
	 * @return the tarea ID of this tarea
	 */
	public long getTareaId();

	/**
	 * Sets the tarea ID of this tarea.
	 *
	 * @param tareaId the tarea ID of this tarea
	 */
	public void setTareaId(long tareaId);

	/**
	 * Returns the user ID of this tarea.
	 *
	 * @return the user ID of this tarea
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tarea.
	 *
	 * @param userId the user ID of this tarea
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tarea.
	 *
	 * @return the user uuid of this tarea
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tarea.
	 *
	 * @param userUuid the user uuid of this tarea
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tarea.
	 *
	 * @return the user name of this tarea
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this tarea.
	 *
	 * @param userName the user name of this tarea
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tarea.
	 *
	 * @return the create date of this tarea
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this tarea.
	 *
	 * @param createDate the create date of this tarea
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tarea.
	 *
	 * @return the modified date of this tarea
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tarea.
	 *
	 * @param modifiedDate the modified date of this tarea
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hora inicio of this tarea.
	 *
	 * @return the hora inicio of this tarea
	 */
	public Date getHoraInicio();

	/**
	 * Sets the hora inicio of this tarea.
	 *
	 * @param horaInicio the hora inicio of this tarea
	 */
	public void setHoraInicio(Date horaInicio);

	/**
	 * Returns the hora fin of this tarea.
	 *
	 * @return the hora fin of this tarea
	 */
	public Date getHoraFin();

	/**
	 * Sets the hora fin of this tarea.
	 *
	 * @param horaFin the hora fin of this tarea
	 */
	public void setHoraFin(Date horaFin);

	/**
	 * Returns the activa of this tarea.
	 *
	 * @return the activa of this tarea
	 */
	public boolean getActiva();

	/**
	 * Returns <code>true</code> if this tarea is activa.
	 *
	 * @return <code>true</code> if this tarea is activa; <code>false</code> otherwise
	 */
	public boolean isActiva();

	/**
	 * Sets whether this tarea is activa.
	 *
	 * @param activa the activa of this tarea
	 */
	public void setActiva(boolean activa);

	/**
	 * Returns the latitud of this tarea.
	 *
	 * @return the latitud of this tarea
	 */
	public double getLatitud();

	/**
	 * Sets the latitud of this tarea.
	 *
	 * @param latitud the latitud of this tarea
	 */
	public void setLatitud(double latitud);

	/**
	 * Returns the longitud of this tarea.
	 *
	 * @return the longitud of this tarea
	 */
	public double getLongitud();

	/**
	 * Sets the longitud of this tarea.
	 *
	 * @param longitud the longitud of this tarea
	 */
	public void setLongitud(double longitud);

	/**
	 * Returns the tipo tarea of this tarea.
	 *
	 * @return the tipo tarea of this tarea
	 */
	public long getTipoTarea();

	/**
	 * Sets the tipo tarea of this tarea.
	 *
	 * @param tipoTarea the tipo tarea of this tarea
	 */
	public void setTipoTarea(long tipoTarea);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tarea tarea);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tarea> toCacheModel();

	@Override
	public Tarea toEscapedModel();

	@Override
	public Tarea toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}