/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.fichajes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TipoTarea service. Represents a row in the &quot;Fichajes_TipoTarea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.vass.fichajes.model.impl.TipoTareaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.vass.fichajes.model.impl.TipoTareaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipoTarea
 * @see es.vass.fichajes.model.impl.TipoTareaImpl
 * @see es.vass.fichajes.model.impl.TipoTareaModelImpl
 * @generated
 */
@ProviderType
public interface TipoTareaModel extends BaseModel<TipoTarea> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo tarea model instance should use the {@link TipoTarea} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo tarea.
	 *
	 * @return the primary key of this tipo tarea
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo tarea.
	 *
	 * @param primaryKey the primary key of this tipo tarea
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tipo tarea ID of this tipo tarea.
	 *
	 * @return the tipo tarea ID of this tipo tarea
	 */
	public long getTipoTareaId();

	/**
	 * Sets the tipo tarea ID of this tipo tarea.
	 *
	 * @param tipoTareaId the tipo tarea ID of this tipo tarea
	 */
	public void setTipoTareaId(long tipoTareaId);

	/**
	 * Returns the nombre of this tipo tarea.
	 *
	 * @return the nombre of this tipo tarea
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this tipo tarea.
	 *
	 * @param nombre the nombre of this tipo tarea
	 */
	public void setNombre(String nombre);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TipoTarea tipoTarea);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TipoTarea> toCacheModel();

	@Override
	public TipoTarea toEscapedModel();

	@Override
	public TipoTarea toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}